### ISSUE TITLE
Можно ли получить доступ к данным?

### ISSUE THREAD

**Issue by gleb-skobinsky** [toskn/diploma#1]
Привет! Я занимаюсь разрешением кореферентности для русского языка, и мне пока удалось найти только 2 корпуса (RuCor и Ru-Eval 2019) по этой задаче. Из-за крошечного объема данных скор достаточно посредственный. 
Можно ли получить доступ к размеченным данным Semantic Hub, если они на русском языке?

**Comment by toskn** [comment]
Добрый день! Данные приватные под NDA. К сожалению, не могу ими поделиться.
